export const xl__theme__theme1 = '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Office Theme">\n'
    + '<a:themeElements>\n'
    + '<a:clrScheme name="Office">\n'
    + '<a:dk1>\n'
    + '<a:sysClr val="windowText" lastClr="000000"/>\n'
    + '</a:dk1>\n'
    + '<a:lt1>\n'
    + '<a:sysClr val="window" lastClr="FFFFFF"/>\n'
    + '</a:lt1>\n'
    + '<a:dk2>\n'
    + '<a:srgbClr val="44546A"/>\n'
    + '</a:dk2>\n'
    + '<a:lt2>\n'
    + '<a:srgbClr val="E7E6E6"/>\n'
    + '</a:lt2>\n'
    + '<a:accent1>\n'
    + '<a:srgbClr val="4472C4"/>\n'
    + '</a:accent1>\n'
    + '<a:accent2>\n'
    + '<a:srgbClr val="ED7D31"/>\n'
    + '</a:accent2>\n'
    + '<a:accent3>\n'
    + '<a:srgbClr val="A5A5A5"/>\n'
    + '</a:accent3>\n'
    + '<a:accent4>\n'
    + '<a:srgbClr val="FFC000"/>\n'
    + '</a:accent4>\n'
    + '<a:accent5>\n'
    + '<a:srgbClr val="5B9BD5"/>\n'
    + '</a:accent5>\n'
    + '<a:accent6>\n'
    + '<a:srgbClr val="70AD47"/>\n'
    + '</a:accent6>\n'
    + '<a:hlink>\n'
    + '<a:srgbClr val="0563C1"/>\n'
    + '</a:hlink>\n'
    + '<a:folHlink>\n'
    + '<a:srgbClr val="954F72"/>\n'
    + '</a:folHlink>\n'
    + '</a:clrScheme>\n'
    + '<a:fontScheme name="Office">\n'
    + '<a:majorFont>\n'
    + '<a:latin typeface="Calibri Light" panose="020F0302020204030204"/>\n'
    + '<a:ea typeface=""/>\n'
    + '<a:cs typeface=""/>\n'
    + '<a:font script="Jpan" typeface="æ¸¸ã´ã·ãã¯ Light"/>\n'
    + '<a:font script="Hang" typeface="ë§ì ê³ ë"/>\n'
    + '<a:font script="Hans" typeface="ç­çº¿ Light"/>\n'
    + '<a:font script="Hant" typeface="æ°ç´°æé«"/>\n'
    + '<a:font script="Arab" typeface="Times New Roman"/>\n'
    + '<a:font script="Hebr" typeface="Times New Roman"/>\n'
    + '<a:font script="Thai" typeface="Tahoma"/>\n'
    + '<a:font script="Ethi" typeface="Nyala"/>\n'
    + '<a:font script="Beng" typeface="Vrinda"/>\n'
    + '<a:font script="Gujr" typeface="Shruti"/>\n'
    + '<a:font script="Khmr" typeface="MoolBoran"/>\n'
    + '<a:font script="Knda" typeface="Tunga"/>\n'
    + '<a:font script="Guru" typeface="Raavi"/>\n'
    + '<a:font script="Cans" typeface="Euphemia"/>\n'
    + '<a:font script="Cher" typeface="Plantagenet Cherokee"/>\n'
    + '<a:font script="Yiii" typeface="Microsoft Yi Baiti"/>\n'
    + '<a:font script="Tibt" typeface="Microsoft Himalaya"/>\n'
    + '<a:font script="Thaa" typeface="MV Boli"/>\n'
    + '<a:font script="Deva" typeface="Mangal"/>\n'
    + '<a:font script="Telu" typeface="Gautami"/>\n'
    + '<a:font script="Taml" typeface="Latha"/>\n'
    + '<a:font script="Syrc" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Orya" typeface="Kalinga"/>\n'
    + '<a:font script="Mlym" typeface="Kartika"/>\n'
    + '<a:font script="Laoo" typeface="DokChampa"/>\n'
    + '<a:font script="Sinh" typeface="Iskoola Pota"/>\n'
    + '<a:font script="Mong" typeface="Mongolian Baiti"/>\n'
    + '<a:font script="Viet" typeface="Times New Roman"/>\n'
    + '<a:font script="Uigh" typeface="Microsoft Uighur"/>\n'
    + '<a:font script="Geor" typeface="Sylfaen"/>\n'
    + '<a:font script="Armn" typeface="Arial"/>\n'
    + '<a:font script="Bugi" typeface="Leelawadee UI"/>\n'
    + '<a:font script="Bopo" typeface="Microsoft JhengHei"/>\n'
    + '<a:font script="Java" typeface="Javanese Text"/>\n'
    + '<a:font script="Lisu" typeface="Segoe UI"/>\n'
    + '<a:font script="Mymr" typeface="Myanmar Text"/>\n'
    + '<a:font script="Nkoo" typeface="Ebrima"/>\n'
    + '<a:font script="Olck" typeface="Nirmala UI"/>\n'
    + '<a:font script="Osma" typeface="Ebrima"/>\n'
    + '<a:font script="Phag" typeface="Phagspa"/>\n'
    + '<a:font script="Syrn" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Syrj" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Syre" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Sora" typeface="Nirmala UI"/>\n'
    + '<a:font script="Tale" typeface="Microsoft Tai Le"/>\n'
    + '<a:font script="Talu" typeface="Microsoft New Tai Lue"/>\n'
    + '<a:font script="Tfng" typeface="Ebrima"/>\n'
    + '</a:majorFont>\n'
    + '<a:minorFont>\n'
    + '<a:latin typeface="Calibri" panose="020F0502020204030204"/>\n'
    + '<a:ea typeface=""/>\n'
    + '<a:cs typeface=""/>\n'
    + '<a:font script="Jpan" typeface="æ¸¸ã´ã·ãã¯"/>\n'
    + '<a:font script="Hang" typeface="ë§ì ê³ ë"/>\n'
    + '<a:font script="Hans" typeface="ç­çº¿"/>\n'
    + '<a:font script="Hant" typeface="æ°ç´°æé«"/>\n'
    + '<a:font script="Arab" typeface="Arial"/>\n'
    + '<a:font script="Hebr" typeface="Arial"/>\n'
    + '<a:font script="Thai" typeface="Tahoma"/>\n'
    + '<a:font script="Ethi" typeface="Nyala"/>\n'
    + '<a:font script="Beng" typeface="Vrinda"/>\n'
    + '<a:font script="Gujr" typeface="Shruti"/>\n'
    + '<a:font script="Khmr" typeface="DaunPenh"/>\n'
    + '<a:font script="Knda" typeface="Tunga"/>\n'
    + '<a:font script="Guru" typeface="Raavi"/>\n'
    + '<a:font script="Cans" typeface="Euphemia"/>\n'
    + '<a:font script="Cher" typeface="Plantagenet Cherokee"/>\n'
    + '<a:font script="Yiii" typeface="Microsoft Yi Baiti"/>\n'
    + '<a:font script="Tibt" typeface="Microsoft Himalaya"/>\n'
    + '<a:font script="Thaa" typeface="MV Boli"/>\n'
    + '<a:font script="Deva" typeface="Mangal"/>\n'
    + '<a:font script="Telu" typeface="Gautami"/>\n'
    + '<a:font script="Taml" typeface="Latha"/>\n'
    + '<a:font script="Syrc" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Orya" typeface="Kalinga"/>\n'
    + '<a:font script="Mlym" typeface="Kartika"/>\n'
    + '<a:font script="Laoo" typeface="DokChampa"/>\n'
    + '<a:font script="Sinh" typeface="Iskoola Pota"/>\n'
    + '<a:font script="Mong" typeface="Mongolian Baiti"/>\n'
    + '<a:font script="Viet" typeface="Arial"/>\n'
    + '<a:font script="Uigh" typeface="Microsoft Uighur"/>\n'
    + '<a:font script="Geor" typeface="Sylfaen"/>\n'
    + '<a:font script="Armn" typeface="Arial"/>\n'
    + '<a:font script="Bugi" typeface="Leelawadee UI"/>\n'
    + '<a:font script="Bopo" typeface="Microsoft JhengHei"/>\n'
    + '<a:font script="Java" typeface="Javanese Text"/>\n'
    + '<a:font script="Lisu" typeface="Segoe UI"/>\n'
    + '<a:font script="Mymr" typeface="Myanmar Text"/>\n'
    + '<a:font script="Nkoo" typeface="Ebrima"/>\n'
    + '<a:font script="Olck" typeface="Nirmala UI"/>\n'
    + '<a:font script="Osma" typeface="Ebrima"/>\n'
    + '<a:font script="Phag" typeface="Phagspa"/>\n'
    + '<a:font script="Syrn" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Syrj" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Syre" typeface="Estrangelo Edessa"/>\n'
    + '<a:font script="Sora" typeface="Nirmala UI"/>\n'
    + '<a:font script="Tale" typeface="Microsoft Tai Le"/>\n'
    + '<a:font script="Talu" typeface="Microsoft New Tai Lue"/>\n'
    + '<a:font script="Tfng" typeface="Ebrima"/>\n'
    + '</a:minorFont>\n'
    + '</a:fontScheme>\n'
    + '<a:fmtScheme name="Office">\n'
    + '<a:fillStyleLst>\n'
    + '<a:solidFill>\n'
    + '<a:schemeClr val="phClr"/>\n'
    + '</a:solidFill>\n'
    + '<a:gradFill rotWithShape="1">\n'
    + '<a:gsLst>\n'
    + '<a:gs pos="0">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="105000"/>\n'
    + '<a:lumMod val="110000"/>\n'
    + '<a:tint val="67000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '<a:gs pos="50000">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="103000"/>\n'
    + '<a:lumMod val="105000"/>\n'
    + '<a:tint val="73000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '<a:gs pos="100000">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="109000"/>\n'
    + '<a:lumMod val="105000"/>\n'
    + '<a:tint val="81000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '</a:gsLst>\n'
    + '<a:lin ang="5400000" scaled="0"/>\n'
    + '</a:gradFill>\n'
    + '<a:gradFill rotWithShape="1">\n'
    + '<a:gsLst>\n'
    + '<a:gs pos="0">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="103000"/>\n'
    + '<a:lumMod val="102000"/>\n'
    + '<a:tint val="94000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '<a:gs pos="50000">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="110000"/>\n'
    + '<a:lumMod val="100000"/>\n'
    + '<a:shade val="100000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '<a:gs pos="100000">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="120000"/>\n'
    + '<a:lumMod val="99000"/>\n'
    + '<a:shade val="78000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '</a:gsLst>\n'
    + '<a:lin ang="5400000" scaled="0"/>\n'
    + '</a:gradFill>\n'
    + '</a:fillStyleLst>\n'
    + '<a:lnStyleLst>\n'
    + '<a:ln w="6350" cap="flat" cmpd="sng" algn="ctr">\n'
    + '<a:solidFill>\n'
    + '<a:schemeClr val="phClr"/>\n'
    + '</a:solidFill>\n'
    + '<a:prstDash val="solid"/>\n'
    + '<a:miter lim="800000"/>\n'
    + '</a:ln>\n'
    + '<a:ln w="12700" cap="flat" cmpd="sng" algn="ctr">\n'
    + '<a:solidFill>\n'
    + '<a:schemeClr val="phClr"/>\n'
    + '</a:solidFill>\n'
    + '<a:prstDash val="solid"/>\n'
    + '<a:miter lim="800000"/>\n'
    + '</a:ln>\n'
    + '<a:ln w="19050" cap="flat" cmpd="sng" algn="ctr">\n'
    + '<a:solidFill>\n'
    + '<a:schemeClr val="phClr"/>\n'
    + '</a:solidFill>\n'
    + '<a:prstDash val="solid"/>\n'
    + '<a:miter lim="800000"/>\n'
    + '</a:ln>\n'
    + '</a:lnStyleLst>\n'
    + '<a:effectStyleLst>\n'
    + '<a:effectStyle>\n'
    + '<a:effectLst/>\n'
    + '</a:effectStyle>\n'
    + '<a:effectStyle>\n'
    + '<a:effectLst/>\n'
    + '</a:effectStyle>\n'
    + '<a:effectStyle>\n'
    + '<a:effectLst>\n'
    + '<a:outerShdw blurRad="57150" dist="19050" dir="5400000" algn="ctr" rotWithShape="0">\n'
    + '<a:srgbClr val="000000">\n'
    + '<a:alpha val="63000"/>\n'
    + '</a:srgbClr>\n'
    + '</a:outerShdw>\n'
    + '</a:effectLst>\n'
    + '</a:effectStyle>\n'
    + '</a:effectStyleLst>\n'
    + '<a:bgFillStyleLst>\n'
    + '<a:solidFill>\n'
    + '<a:schemeClr val="phClr"/>\n'
    + '</a:solidFill>\n'
    + '<a:solidFill>\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:tint val="95000"/>\n'
    + '<a:satMod val="170000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:solidFill>\n'
    + '<a:gradFill rotWithShape="1">\n'
    + '<a:gsLst>\n'
    + '<a:gs pos="0">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="150000"/>\n'
    + '<a:lumMod val="102000"/>\n'
    + '<a:tint val="93000"/>\n'
    + '<a:shade val="98000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '<a:gs pos="50000">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="130000"/>\n'
    + '<a:lumMod val="103000"/>\n'
    + '<a:tint val="98000"/>\n'
    + '<a:shade val="90000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '<a:gs pos="100000">\n'
    + '<a:schemeClr val="phClr">\n'
    + '<a:satMod val="120000"/>\n'
    + '<a:shade val="63000"/>\n'
    + '</a:schemeClr>\n'
    + '</a:gs>\n'
    + '</a:gsLst>\n'
    + '<a:lin ang="5400000" scaled="0"/>\n'
    + '</a:gradFill>\n'
    + '</a:bgFillStyleLst>\n'
    + '</a:fmtScheme>\n'
    + '</a:themeElements>\n'
    + '<a:objectDefaults/>\n'
    + '<a:extraClrSchemeLst/>\n'
    + '</a:theme>';