export const xl__worksheets__sheet1: string = '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><worksheet xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">\n'
    + '<sheetPr>\n'
    + '<outlinePr summaryBelow="0"/>\n'
    + '</sheetPr>\n'
    + '<sheetFormatPr baseColWidth="10" defaultRowHeight="16"/>\n'
    + '<cols>\n'
    + '<col min="1" max="1" width="19" hidden="0" bestFit="0" customWidth="1"/>\n'
    + '<col min="2" max="2" width="19" hidden="0" bestFit="0" customWidth="1"/>\n'
    + '<col min="3" max="3" width="19" hidden="0" bestFit="0" customWidth="1"/>\n'
    + '<col min="4" max="4" width="19" hidden="0" bestFit="0" customWidth="1"/>\n'
    + '<col min="5" max="5" width="19" hidden="0" bestFit="0" customWidth="1"/>\n'
    + '</cols>\n'
    + '<sheetData>\n'
    + '<row r="1" collapsed="0" hidden="0" customHeight="0" spans="1:1">\n'
    + '<c r="A1" t="s">\n'
    + '<v>0</v>\n'
    + '</c>\n'
    + '<c r="B1" t="s">\n'
    + '<v>1</v>\n'
    + '</c>\n'
    + '<c r="C1" t="s">\n'
    + '<v>2</v>\n'
    + '</c>\n'
    + '<c r="D1" t="s">\n'
    + '<v>3</v>\n'
    + '</c>\n'
    + '<c r="E1" t="s">\n'
    + '<v>4</v>\n'
    + '</c>\n'
    + '</row>\n'
    + '<row r="2" collapsed="0" hidden="0" customHeight="0" spans="1:1">\n'
    + '<c r="A2" t="s">\n'
    + '<v>5</v>\n'
    + '</c>\n'
    + '<c r="B2" t="s">\n'
    + '<v>6</v>\n'
    + '</c>\n'
    + '<c r="C2" t="n">\n'
    + '<v>2008</v>\n'
    + '</c>\n'
    + '<c r="D2" t="s">\n'
    + '<v>7</v>\n'
    + '</c>\n'
    + '<c r="E2" t="n">\n'
    + '<v>8</v>\n'
    + '</c>\n'
    + '</row>\n'
    + '<row r="3" collapsed="0" hidden="0" customHeight="0" spans="1:1">\n'
    + '<c r="A3" t="s">\n'
    + '<v>5</v>\n'
    + '</c>\n'
    + '<c r="B3" t="s">\n'
    + '<v>6</v>\n'
    + '</c>\n'
    + '<c r="C3" t="n">\n'
    + '<v>2004</v>\n'
    + '</c>\n'
    + '<c r="D3" t="s">\n'
    + '<v>7</v>\n'
    + '</c>\n'
    + '<c r="E3" t="n">\n'
    + '<v>8</v>\n'
    + '</c>\n'
    + '</row>\n'
    + '</sheetData>\n'
    + '<pageMargins bottom="0.75" footer="0.3" header="0.3" left="0.7" right="0.7" top="0.75"/>\n'
    + '</worksheet>\n';