export const xl__sharedStrings = '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="8" uniqueCount="8">\n'
    + '<si>\n'
    + '<t>Athlete</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>Country</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>Year</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>Sport</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>Total</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>Michael Phelps</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>United States</t>\n'
    + '</si>\n'
    + '<si>\n'
    + '<t>Swimming</t>\n'
    + '</si>\n'
    + '</sst>';