export const xl__styles = '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><styleSheet mc:Ignorable="x14ac x16r2 xr" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:x16r2="http://schemas.microsoft.com/office/spreadsheetml/2015/02/main" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision">\n'
    + '<numFmts count="0">\n'
    + '</numFmts>\n'
    + '<fonts count="1">\n'
    + '<font>\n'
    + '<sz val="11"/>\n'
    + '<color theme="1" rgb="FF000000"/>\n'
    + '<name val="Calibri"/>\n'
    + '<family val="2"/>\n'
    + '<scheme val="minor"/>\n'
    + '</font>\n'
    + '</fonts>\n'
    + '<fills count="2">\n'
    + '<fill>\n'
    + '<patternFill patternType="none"/>\n'
    + '</fill>\n'
    + '<fill>\n'
    + '<patternFill patternType="gray125"/>\n'
    + '</fill>\n'
    + '</fills>\n'
    + '<borders count="1">\n'
    + '<border>\n'
    + '<left/>\n'
    + '<right/>\n'
    + '<top/>\n'
    + '<bottom/>\n'
    + '<diagonal/>\n'
    + '</border>\n'
    + '</borders>\n'
    + '<cellStyleXfs count="1">\n'
    + '<xf borderId="0" fillId="0" fontId="0" numFmtId="0"/>\n'
    + '</cellStyleXfs>\n'
    + '<cellXfs count="1">\n'
    + '<xf borderId="0" fillId="0" fontId="0" numFmtId="0" xfId="0"/>\n'
    + '</cellXfs>\n'
    + '<cellStyles count="1">\n'
    + '<cellStyle builtinId="0" name="Normal" xfId="0"/>\n'
    + '</cellStyles>\n'
    + '<tableStyles count="0" defaultPivotStyle="PivotStyleLight16" defaultTableStyle="TableStyleMedium2"/>\n'
    + '</styleSheet>';